# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoVCpp.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 581)
        MainWindow.setMinimumSize(QtCore.QSize(621, 581))
        MainWindow.setMaximumSize(QtCore.QSize(621, 581))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 170, 491, 335))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vc2008x64 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2008x64.setFont(font)
        self.vc2008x64.setObjectName("vc2008x64")
        self.verticalLayout.addWidget(self.vc2008x64)
        self.vc2008x86 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2008x86.setFont(font)
        self.vc2008x86.setObjectName("vc2008x86")
        self.verticalLayout.addWidget(self.vc2008x86)
        self.vc2010x64 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2010x64.setFont(font)
        self.vc2010x64.setObjectName("vc2010x64")
        self.verticalLayout.addWidget(self.vc2010x64)
        self.vc2010x86 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2010x86.setFont(font)
        self.vc2010x86.setObjectName("vc2010x86")
        self.verticalLayout.addWidget(self.vc2010x86)
        self.vc2012x64 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2012x64.setFont(font)
        self.vc2012x64.setObjectName("vc2012x64")
        self.verticalLayout.addWidget(self.vc2012x64)
        self.vc2012x86 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2012x86.setFont(font)
        self.vc2012x86.setObjectName("vc2012x86")
        self.verticalLayout.addWidget(self.vc2012x86)
        self.vc2013x64 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2013x64.setFont(font)
        self.vc2013x64.setObjectName("vc2013x64")
        self.verticalLayout.addWidget(self.vc2013x64)
        self.vc2013x86 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2013x86.setFont(font)
        self.vc2013x86.setObjectName("vc2013x86")
        self.verticalLayout.addWidget(self.vc2013x86)
        self.vc2015to19x64 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2015to19x64.setFont(font)
        self.vc2015to19x64.setObjectName("vc2015to19x64")
        self.verticalLayout.addWidget(self.vc2015to19x64)
        self.vc2015to19x86 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.vc2015to19x86.setFont(font)
        self.vc2015to19x86.setObjectName("vc2015to19x86")
        self.verticalLayout.addWidget(self.vc2015to19x86)
        self.Install = QtWidgets.QPushButton(self.centralwidget)
        self.Install.setGeometry(QtCore.QRect(500, 530, 93, 31))
        self.Install.setObjectName("Install")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 72, 15))
        self.label_3.setObjectName("label_3")
        self.SelectAll = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectAll.setGeometry(QtCore.QRect(60, 140, 91, 31))
        self.SelectAll.setObjectName("SelectAll")
        self.InstallTip = QtWidgets.QLabel(self.centralwidget)
        self.InstallTip.setGeometry(QtCore.QRect(80, 510, 491, 16))
        self.InstallTip.setObjectName("InstallTip")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "安装向导 - Visual C++运行库合集"))
        self.label.setText(_translate("MainWindow", "选择组件"))
        self.label_2.setText(_translate("MainWindow", "要安装哪些组件？"))
        self.vc2008x64.setText(_translate("MainWindow", "Microsoft Visual C++ 2008 Redistributable (x64)"))
        self.vc2008x86.setText(_translate("MainWindow", "Microsoft Visual C++ 2008 Redistributable (x86)"))
        self.vc2010x64.setText(_translate("MainWindow", "Microsoft Visual C++ 2010 Redistributable (x64)"))
        self.vc2010x86.setText(_translate("MainWindow", "Microsoft Visual C++ 2010 Redistributable (x86)"))
        self.vc2012x64.setText(_translate("MainWindow", "Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030"))
        self.vc2012x86.setText(_translate("MainWindow", "Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030"))
        self.vc2013x64.setText(_translate("MainWindow", "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664"))
        self.vc2013x86.setText(_translate("MainWindow", "Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664"))
        self.vc2015to19x64.setText(_translate("MainWindow", "Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.24.28127"))
        self.vc2015to19x86.setText(_translate("MainWindow", "Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.24.28127"))
        self.Install.setText(_translate("MainWindow", "安装"))
        self.label_3.setText(_translate("MainWindow", "选择组件"))
        self.SelectAll.setText(_translate("MainWindow", "全选"))
        self.InstallTip.setText(_translate("MainWindow", "选择后请点击安装按钮！"))
